// tests read and write of memory_mod
// writes data to consecutive memory addresses
// reads previous values and displays value on LEDs

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LEDMemoryTest(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// RST_N //////////
	input 		     			RST_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	// reg w_en;
	// reg[15:0] d_in;
	// reg[14:0] r_addr, w_addr;
	// wire[15:0] d_out;

	reg[27:0] 	counter;
	wire 		maxcount;
	reg[15:0] 	d_in;
	reg[14:0] 	w_addr, r_addr;
	wire[15:0] 	d_out;
	reg 		w_en;
	
	reg[7:0] 	led_cnt;


//=======================================================
//  Structural coding
//=======================================================
memory_mod MEMORYTHANG(w_en, d_in, d_out, r_addr, w_addr, CLOCK_50, RST_N);



//counter shtuff
always @(posedge CLOCK_50, negedge RST_N) begin
	if(!RST_N) counter <= 20'h0;
	else begin
	 counter <= counter + 1;
	end 
end

assign maxcount = (counter == 28'd268400000) ? 1 : 0;

always @(posedge CLOCK_50, negedge RST_N) begin
	if(!RST_N) begin
		w_addr 	<= 15'h0;
		r_addr 	<= 0;
		w_addr 	<= 0;
		d_in 	<= 0;
		w_en 	<= 0;
	end
	else begin
		if(maxcount) begin
			w_en 		<= 1;
			r_addr 		<= led_cnt;
			w_addr 		<= led_cnt;
			d_in 		<= led_cnt;
			led_cnt 	<= led_cnt + 1;
			
		end else w_en 	<= 0;
	end
end

assign LED[7:0] = d_out[7:0];



endmodule
