
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LEDMemoryTest(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// RST_N //////////
	input 		     			RST_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	// reg w_en;
	// reg[15:0] d_in;
	// reg[14:0] r_addr, w_addr;
	// wire[15:0] d_out;

	reg[23:0] 	counter;

	wire 		maxcount;
	wire[15:0] 	d_in;
	wire[15:0] 	w_addr, r_addr;
	wire[15:0] 	d_out;
	wire 		w_en;
	
	reg[11:0] 	led_cnt;


//=======================================================
//  Structural coding
//=======================================================
memory_mod MEMORYTHANG(w_en, d_in, d_out, r_addr, w_addr, CLOCK_50, RST_N);



//counter stuff
always @(posedge CLOCK_50, negedge RST_N) begin
	if(!RST_N) counter <= 28'h0;
	else begin
	 counter <= counter + 1;
	end 
end

assign maxcount = (&counter);

always @(posedge CLOCK_50, negedge RST_N) begin
	if(!RST_N) begin
		led_cnt <= 0;
	end
	else begin
		if(maxcount) begin
			
			led_cnt 	<= led_cnt + 1;
			
		end
	end
end

assign LED[7:0] = d_out[7:0];

assign r_addr 	= led_cnt - 13'h1;
assign w_addr	= led_cnt;
assign d_in 	= led_cnt;
assign w_en 	= maxcount;


endmodule
